{% set name = "envparse" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f3b9a27bb55d27f124eb4adf006fec05e4588891c9a054a183a112645056eb7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: https://github.com/rconradharris/envparse
  license: MIT
  license_family: MIT
  license_file: 
  summary: Simple environment variable parsing
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
