{% set data = load_setup_py_data() %}

package:
    name: pymor
    version: {{ data['version'] }}

source:
  git_url: https://github.com/pymor/pymor.git

extra:
  channels:
    - pymor

requirements:
  build:
    {% for dep in data['setup_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    - python
    - pyqt
    - matplotlib
    - pyopengl

    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    {% for dep in data['tests_require'] %}
    - {{ dep.lower() }}
    {% endfor %}

  commands:
    - pymor-demo

  imports:
    - pymor

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}

